FROM golang:tip-alpine3.22 AS builder

WORKDIR /app

COPY main.go go.mod ./

RUN go mod download

RUN go build -o hello .

FROM scratch

WORKDIR /app

# Copy the compiled binary from the previous stage
COPY --from=builder /app/hello .

ENTRYPOINT ["./hello"]

